name: Build macOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build macOS
      run: npm run build
    
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist-release/*.dmg